fragment PagesParts on Pages {
  __typename
  title
  body
}

fragment SidebarParts on Sidebar {
  __typename
  items {
    __typename
    type
    label
    id
    items {
      __typename
      type
      label
      id
    }
  }
}
