fragment PagesParts on Pages {
  __typename
  title
  body
}

fragment DecksParts on Decks {
  __typename
  title
  deckPath
  body
}

fragment SidebarsParts on Sidebars {
  __typename
  daSidebar {
    __typename
    type
    id
    label
    collapsed
    items {
      __typename
      type
      id
      label
    }
  }
  takSidebar {
    __typename
    type
    id
    label
    collapsed
    items {
      __typename
      type
      id
      label
    }
  }
  blSidebar {
    __typename
    type
    id
    label
    collapsed
    items {
      __typename
      type
      id
      label
    }
  }
  iosDaSidebar {
    __typename
    type
    id
    label
    collapsed
    items {
      __typename
      type
      id
      label
    }
  }
  iosTakSidebar {
    __typename
    type
    id
    label
    collapsed
    items {
      __typename
      type
      id
      label
    }
  }
  iosBlSidebar {
    __typename
    type
    id
    label
    collapsed
    items {
      __typename
      type
      id
      label
    }
  }
  winDaSidebar {
    __typename
    type
    id
    label
    collapsed
    items {
      __typename
      type
      id
      label
    }
  }
  winTakSidebar {
    __typename
    type
    id
    label
    collapsed
    items {
      __typename
      type
      id
      label
    }
  }
  winBlSidebar {
    __typename
    type
    id
    label
    collapsed
    items {
      __typename
      type
      id
      label
    }
  }
  devSidebar {
    __typename
    type
    id
    label
    collapsed
    items {
      __typename
      type
      id
      label
    }
  }
}
