module.exports = {
  devSidebar: [
    {
      type: 'autogenerated',
      dirName: 'dev',
    },
  ],
  daSidebar: [
    {
      type: 'autogenerated',
      dirName: 'deployapp',
    },
  ],
  takSidebar: [
    {
      type: 'autogenerated',
      dirName: 'tak',
    },
  ],
  blSidebar: [
    {
      type: 'autogenerated',
      dirName: 'bl',
    },
  ],
};
