// sidebar.js
// Generate Docusaurus sidebars from Tina-edited JSON at src/sidebars/sidebars.json
// with robust fallbacks for missing docs and empty categories.

const path = require('path');
const fs = require('fs');

const jsonPath = path.resolve(__dirname, 'src/sidebars/sidebars.json');
const docsRoot = path.resolve(__dirname, 'docs');

function fileExistsNoExt(id) {
  const md  = path.join(docsRoot, id + '.md');
  const mdx = path.join(docsRoot, id + '.mdx');
  return fs.existsSync(md) || fs.existsSync(mdx);
}

function dirExists(id) {
  const p = path.join(docsRoot, id);
  return fs.existsSync(p) && fs.lstatSync(p).isDirectory();
}

function toSlug(s) {
  return String(s || 'overview').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
}

/**
 * Resolve a logical "doc id" to a concrete one that exists.
 * Tries:
 *  - id
 *  - id/index
 *  - if id ends with /home → try parent (id without /home), then parent/index
 *  - id/README (common for dev docs)
 */
function resolveDocId(id) {
  if (!id) return null;
  if (fileExistsNoExt(id)) return id;

  const idx = path.posix.join(id, 'index');
  if (fileExistsNoExt(idx)) return idx;

  const parts = id.split('/');
  if (parts[parts.length - 1] === 'home') {
    const parent = parts.slice(0, -1).join('/');
    if (fileExistsNoExt(parent)) return parent;
    const parentIdx = path.posix.join(parent, 'index');
    if (fileExistsNoExt(parentIdx)) return parentIdx;
  }

  const readme = path.posix.join(id, 'README');
  if (fileExistsNoExt(readme)) return readme;

  return null;
}

let cfg;
try {
  cfg = JSON.parse(fs.readFileSync(jsonPath, 'utf8'));
} catch (e) {
  console.warn('[sidebar.js] Could not read src/sidebars/sidebars.json; using empty sidebars.', e.message);
  cfg = {};
}

/** Map Tina JSON items → Docusaurus sidebar items with fallbacks */
function mapItems(items, trail = []) {
  if (!Array.isArray(items)) return [];
  return items.flatMap((it, idx) => {
    const pfx = trail.concat(`${it?.type || 'item'}#${idx}`).join(' > ');

    if (it.type === 'doc') {
      const resolved = resolveDocId(it.id || '');
      if (resolved) {
        return it.label ? { type: 'doc', id: resolved, label: it.label } : { type: 'doc', id: resolved };
      }
      // If the "doc" is actually a folder, turn it into an autogenerated category
      if (dirExists(it.id || '')) {
        const label = it.label || (it.id.split('/').slice(-1)[0] || 'Section');
        return {
          type: 'category',
          label,
          collapsed: typeof it.collapsed === 'boolean' ? it.collapsed : true,
          items: [{ type: 'autogenerated', dirName: it.id }],
        };
      }
      console.warn(`[sidebar.js] Skipping unknown doc id "${it.id}" at ${pfx}`);
      return []; // drop unknown doc to avoid crashes
    }

    // category
    const children = mapItems(it.items || [], trail.concat(`category#${idx}`));
    if (children.length === 0) {
      // Avoid Docusaurus error: category must have items or a link
      const label = it.label || 'Category';
      return {
        type: 'category',
        label,
        collapsed: typeof it.collapsed === 'boolean' ? it.collapsed : true,
        link: { type: 'generated-index', title: label, slug: `/auto/${toSlug(label)}` },
        items: [],
      };
    }
    return {
      type: 'category',
      label: it.label || 'Category',
      collapsed: typeof it.collapsed === 'boolean' ? it.collapsed : true,
      items: children,
    };
  });
}

function buildSidebar(nameInCfg, exportName) {
  const arr = cfg[nameInCfg] || [];
  return { [exportName]: mapItems(arr, [exportName]) };
}

module.exports = {
  // Android
  ...buildSidebar('daSidebar',  'androidDeployapp'),
  ...buildSidebar('takSidebar', 'androidTak'),
  ...buildSidebar('blSidebar',  'androidBattlelog'),

  // iOS
  ...buildSidebar('iosDaSidebar',  'iosDeployapp'),
  ...buildSidebar('iosTakSidebar', 'iosTak'),
  ...buildSidebar('iosBlSidebar',  'iosBattlelog'),

  // Windows
  ...buildSidebar('winDaSidebar',  'windowsDeployapp'),
  ...buildSidebar('winTakSidebar', 'windowsTak'),
  ...buildSidebar('winBlSidebar',  'windowsBattlelog'),

  // Developer
  ...buildSidebar('devSidebar', 'developer'),
};
