module.exports = {
  developer: [
    { type: 'doc', id: 'dev/index', label: 'Overview' },

    {
      type: 'category',
      label: 'Contributing',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'dev/contributing' }],
    },
    {
      type: 'category',
      label: 'Specs',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'dev/specs' }],
    },
    {
      type: 'category',
      label: 'Roadmap',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'dev/roadmap' }],
    },
    {
      type: 'category',
      label: 'Setup Guide',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'dev/setupguide' }],
    },
    {
      type: 'category',
      label: "Repositories & Readme's",
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'dev/integrationrepo' }],
    },
    {
      type: 'category',
      label: 'API Docs',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'dev/autoapidocs' }],
    },
  ],
};
