module.exports = {
  devSidebar: [
    {
      type: 'autogenerated',
      dirName: 'dev', // Generate sidebar slice from docs/dev
    },
  ],
  userSidebar: [
    {
      type: 'autogenerated',
      dirName: 'user', // Generate sidebar slice from docs/user
    },
  ],
};