name: outlineSync
on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  sync-outline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install outline-sync

      - name: Sync Outline
        run: outline-sync --config ${{ github.workspace }}/src/scripts/outline_sync_config.json

      - name: Commit Changes
        run: |
          git add .
          git commit -m "Sync Outline" || echo "No changes to commit"
          git push origin main
      - name: Notify Completion
        run: echo "Outline sync completed successfully."
      - name: Debug
        run: |
          echo "Current directory contents:"
          ls -la
          echo "Git status:"
          git status
          echo "Last commit:"
          git log -1
          echo "Outline sync completed."
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: outline-sync-artifact